import type { Metadata } from "next";
import { Italiana, Poppins } from 'next/font/google';
import "./globals.css";


const italianaFont = Italiana({
  subsets : ["latin"],
  weight : "400"
})

const poppinsFont = Poppins({
  subsets : ["latin"],
  weight : "800",
})

export const metadata: Metadata = {
  title: "Stratosphere's Art",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
